package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

/**
 * TApplyownerresult generated by hbm2java
 */
public class ApplyOwnerResult implements java.io.Serializable {

	private int id;
	private Integer userId;
	private Integer tiebaName;
	private Byte result;

	public ApplyOwnerResult() {
	}

	public ApplyOwnerResult(int id) {
		this.id = id;
	}

	public ApplyOwnerResult(int id, Integer userId, Integer tiebaName,
			Byte result) {
		this.id = id;
		this.userId = userId;
		this.tiebaName = tiebaName;
		this.result = result;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getTiebaName() {
		return this.tiebaName;
	}

	public void setTiebaName(Integer tiebaName) {
		this.tiebaName = tiebaName;
	}

	public Byte getResult() {
		return this.result;
	}

	public void setResult(Byte result) {
		this.result = result;
	}

}
