package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

/**
 * TApplyownerresult generated by hbm2java
 */
public class ApplyOwnerResult implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String tiebaName;
	private Byte result;

	public ApplyOwnerResult() {
	}

	public ApplyOwnerResult(Integer id) {
		this.id = id;
	}

	public ApplyOwnerResult(Integer id, Integer userId, String tiebaName,
			Byte result) {
		super();
		this.id = id;
		this.userId = userId;
		this.tiebaName = tiebaName;
		this.result = result;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getTiebaName() {
		return tiebaName;
	}

	public void setTiebaName(String tiebaName) {
		this.tiebaName = tiebaName;
	}

	public Byte getResult() {
		return this.result;
	}

	public void setResult(Byte result) {
		this.result = result;
	}

}
