package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

/**
 * TManager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer id;
	private String managername;
	private String pwd;

	public Manager() {
	}

	public Manager(int id) {
		this.id = id;
	}

	public Manager(int id, String managername, String password) {
		this.id = id;
		this.managername = managername;
		this.pwd = password;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getManagername() {
		return this.managername;
	}

	public void setManagername(String managername) {
		this.managername = managername;
	}

	public String getPassword() {
		return this.pwd;
	}

	public void setPassword(String password) {
		this.pwd = password;
	}

}
