package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

/**
 * TManager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer id;
	private String managername;
	private String pwd;
	private Byte tiabaApplyRead;
	private Byte tiebaOwnerApplyRead;

	public Manager() {
	}

	public Manager(Integer id) {
		this.id = id;
	}

	public Manager(Integer id, String managername, String pwd) {
		this.id = id;
		this.managername = managername;
		this.pwd = pwd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getManagername() {
		return this.managername;
	}

	public void setManagername(String managername) {
		this.managername = managername;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Byte getTiabaApplyRead() {
		return tiabaApplyRead;
	}

	public void setTiabaApplyRead(Byte tiabaApplyRead) {
		this.tiabaApplyRead = tiabaApplyRead;
	}

	public Byte getTiebaOwnerApplyRead() {
		return tiebaOwnerApplyRead;
	}

	public void setTiebaOwnerApplyRead(Byte tiebaOwnerApplyRead) {
		this.tiebaOwnerApplyRead = tiebaOwnerApplyRead;
	}

	

}
