package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TReply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private Integer id;
	private Tie tie;
	private TieTitle tieTitle;
	private User sendUser;
	private User beSendUser;
	private String body;
	private Date createDate;

	public Reply() {
	}

	public Reply(Integer id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}



	public Reply(Integer id, Tie tie, TieTitle tieTitle, User sendUser,
			User beSendUser, String body, Date createDate) {
		super();
		this.id = id;
		this.tie = tie;
		this.tieTitle = tieTitle;
		this.sendUser = sendUser;
		this.beSendUser = beSendUser;
		this.body = body;
		this.createDate = createDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tie getTie() {
		return this.tie;
	}

	public void setTie(Tie tie) {
		this.tie = tie;
	}

	public TieTitle getTieTitle() {
		return this.tieTitle;
	}

	public void setTieTitle(TieTitle tieTitle) {
		this.tieTitle = tieTitle;
	}

	public User getSendUser() {
		return sendUser;
	}

	public void setSendUser(User sendUser) {
		this.sendUser = sendUser;
	}

	public User getBeSendUser() {
		return beSendUser;
	}

	public void setBeSendUser(User beSendUser) {
		this.beSendUser = beSendUser;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
