package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TReply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private int id;
	private Tie Tie;
	private TieTitle TieTitle;
	private Integer sendUserId;
	private Integer beSendUserId;
	private String body;
	private Integer belongFloor;
	private Date createDate;

	public Reply() {
	}

	public Reply(int id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	public Reply(int id, Tie Tie, TieTitle TieTitle, Integer sendUserId,
			Integer beSendUserId, String body, Integer belongFloor,
			Date createDate) {
		this.id = id;
		this.Tie = Tie;
		this.TieTitle = TieTitle;
		this.sendUserId = sendUserId;
		this.beSendUserId = beSendUserId;
		this.body = body;
		this.belongFloor = belongFloor;
		this.createDate = createDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tie getTie() {
		return this.Tie;
	}

	public void setTie(Tie Tie) {
		this.Tie = Tie;
	}

	public TieTitle getTieTitle() {
		return this.TieTitle;
	}

	public void setTieTitle(TieTitle TieTitle) {
		this.TieTitle = TieTitle;
	}

	public Integer getSendUserId() {
		return this.sendUserId;
	}

	public void setSendUserId(Integer sendUserId) {
		this.sendUserId = sendUserId;
	}

	public Integer getBeSendUserId() {
		return this.beSendUserId;
	}

	public void setBeSendUserId(Integer beSendUserId) {
		this.beSendUserId = beSendUserId;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Integer getBelongFloor() {
		return this.belongFloor;
	}

	public void setBelongFloor(Integer belongFloor) {
		this.belongFloor = belongFloor;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
