package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TTie generated by hbm2java
 */
public class Tie implements java.io.Serializable {

	private int id;
	private TieTitle TieTitle;
	private Integer sendUserId;
	private Integer beSendUserId;
	private Integer floor;
	private String body;
	private Date createdDate;
	private Set TReplies = new HashSet(0);

	public Tie() {
	}

	public Tie(int id, Date createdDate) {
		this.id = id;
		this.createdDate = createdDate;
	}

	public Tie(int id, TieTitle TieTitle, Integer sendUserId,
			Integer beSendUserId, Integer floor, String body, Date createdDate,
			Set TReplies) {
		this.id = id;
		this.TieTitle = TieTitle;
		this.sendUserId = sendUserId;
		this.beSendUserId = beSendUserId;
		this.floor = floor;
		this.body = body;
		this.createdDate = createdDate;
		this.TReplies = TReplies;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TieTitle getTieTitle() {
		return this.TieTitle;
	}

	public void setTieTitle(TieTitle TieTitle) {
		this.TieTitle = TieTitle;
	}

	public Integer getSendUserId() {
		return this.sendUserId;
	}

	public void setSendUserId(Integer sendUserId) {
		this.sendUserId = sendUserId;
	}

	public Integer getBeSendUserId() {
		return this.beSendUserId;
	}

	public void setBeSendUserId(Integer beSendUserId) {
		this.beSendUserId = beSendUserId;
	}

	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set getTReplies() {
		return this.TReplies;
	}

	public void setTReplies(Set TReplies) {
		this.TReplies = TReplies;
	}

}
