package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TTie generated by hbm2java
 */
public class Tie implements java.io.Serializable {

	private Integer id;
	private TieTitle tieTitle;
	private User sendUser;
	private User beSendUser;
	private Integer floor;
	private String body;
	private Date createDate;
	private Set replies = new HashSet();
	
	public Tie() {
	}
	
	public Tie(String body,String title,String sendUsername) {
		this.body=body;
		this.tieTitle = new TieTitle();
		this.tieTitle.setTitle(title);
		this.sendUser = new User();
		this.sendUser.setUsername(sendUsername);
	}

	public Tie(Integer id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	public Tie(Integer id, TieTitle tieTitle, User sendUser, User beSendUser,
			Integer floor, String body, Date createDate, Set replies) {
		super();
		this.id = id;
		this.tieTitle = tieTitle;
		this.sendUser = sendUser;
		this.beSendUser = beSendUser;
		this.floor = floor;
		this.body = body;
		this.createDate = createDate;
		this.replies = replies;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TieTitle getTieTitle() {
		return this.tieTitle;
	}

	public void setTieTitle(TieTitle tieTitle) {
		this.tieTitle = tieTitle;
	}


	public User getSendUser() {
		return sendUser;
	}

	public void setSendUser(User sendUser) {
		this.sendUser = sendUser;
	}

	public User getBeSendUser() {
		return beSendUser;
	}

	public void setBeSendUser(User beSendUser) {
		this.beSendUser = beSendUser;
	}

	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}


	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set Replies) {
		this.replies = Replies;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
