package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TTieba generated by hbm2java
 */
public class Tieba implements java.io.Serializable {

	private int id;
	private String tiebaName;
	private String headImg;
	private String bgImg;
	private String intruduction;
	private Boolean enabled;
	private Set TUserTiebas = new HashSet(0);
	private Set TTietitles = new HashSet(0);

	public Tieba() {
	}

	public Tieba(int id) {
		this.id = id;
	}

	public Tieba(int id, String tiebaName, String headImg, String bgImg,
			String intruduction, Boolean enabled, Set TUserTiebas,
			Set TTietitles) {
		this.id = id;
		this.tiebaName = tiebaName;
		this.headImg = headImg;
		this.bgImg = bgImg;
		this.intruduction = intruduction;
		this.enabled = enabled;
		this.TUserTiebas = TUserTiebas;
		this.TTietitles = TTietitles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTiebaName() {
		return this.tiebaName;
	}

	public void setTiebaName(String tiebaName) {
		this.tiebaName = tiebaName;
	}

	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getBgImg() {
		return this.bgImg;
	}

	public void setBgImg(String bgImg) {
		this.bgImg = bgImg;
	}

	public String getIntruduction() {
		return this.intruduction;
	}

	public void setIntruduction(String intruduction) {
		this.intruduction = intruduction;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Set getTUserTiebas() {
		return this.TUserTiebas;
	}

	public void setTUserTiebas(Set TUserTiebas) {
		this.TUserTiebas = TUserTiebas;
	}

	public Set getTTietitles() {
		return this.TTietitles;
	}

	public void setTTietitles(Set TTietitles) {
		this.TTietitles = TTietitles;
	}

}
