package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTiebaapply generated by hbm2java
 */
public class TiebaApply implements java.io.Serializable {

	private Integer id;
	private String tiebaName;
	private Byte handleStatus;
	private Date applyDate;

	public TiebaApply() {
	}

	public TiebaApply(Integer id, String tiebarName, Date applyDate) {
		this.id = id;
		this.tiebaName = tiebarName;
		this.applyDate = applyDate;
	}

	public TiebaApply(Integer id, String tiebarName, Byte handleStatus,
			Date applyDate) {
		this.id = id;
		this.tiebaName = tiebarName;
		this.handleStatus = handleStatus;
		this.applyDate = applyDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTiebarName() {
		return this.tiebaName;
	}

	public void setTiebarName(String tiebarName) {
		this.tiebaName = tiebarName;
	}

	public Byte getHandleStatus() {
		return this.handleStatus;
	}

	public void setHandleStatus(Byte handleStatus) {
		this.handleStatus = handleStatus;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

}
