package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TTiebaapply generated by hbm2java
 */
public class TiebaApply implements java.io.Serializable {

	private String id;
	private String tiebarName;
	private Byte handleStatus;
	private Date applyDate;

	public TiebaApply() {
	}

	public TiebaApply(String id, String tiebarName, Date applyDate) {
		this.id = id;
		this.tiebarName = tiebarName;
		this.applyDate = applyDate;
	}

	public TiebaApply(String id, String tiebarName, Byte handleStatus,
			Date applyDate) {
		this.id = id;
		this.tiebarName = tiebarName;
		this.handleStatus = handleStatus;
		this.applyDate = applyDate;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTiebarName() {
		return this.tiebarName;
	}

	public void setTiebarName(String tiebarName) {
		this.tiebarName = tiebarName;
	}

	public Byte getHandleStatus() {
		return this.handleStatus;
	}

	public void setHandleStatus(Byte handleStatus) {
		this.handleStatus = handleStatus;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

}
