package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private String username;
	private String nickname;
	private String password;
	private String headImg;
	private String introduction;
	private Byte gender;
	private String birthday;
	private Integer tieCount;
	private Date createdDate;
	private Byte tieRead;
	private Byte replyRead;
	private Byte allpyResultRead;
	private Boolean enabled;
	private Set TUserTiebas = new HashSet(0);
	private Set TTietitles = new HashSet(0);

	public User() {
	}

	public User(int id, String username, Date createdDate) {
		this.id = id;
		this.username = username;
		this.createdDate = createdDate;
	}

	public User(int id, String username, String nickname, String password,
			String headImg, String introduction, Byte gender, String birthday,
			Integer tieCount, Date createdDate, Byte tieRead, Byte replyRead,
			Byte allpyResultRead, Boolean enabled, Set TUserTiebas,
			Set TTietitles) {
		this.id = id;
		this.username = username;
		this.nickname = nickname;
		this.password = password;
		this.headImg = headImg;
		this.introduction = introduction;
		this.gender = gender;
		this.birthday = birthday;
		this.tieCount = tieCount;
		this.createdDate = createdDate;
		this.tieRead = tieRead;
		this.replyRead = replyRead;
		this.allpyResultRead = allpyResultRead;
		this.enabled = enabled;
		this.TUserTiebas = TUserTiebas;
		this.TTietitles = TTietitles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Byte getGender() {
		return this.gender;
	}

	public void setGender(Byte gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Integer getTieCount() {
		return this.tieCount;
	}

	public void setTieCount(Integer tieCount) {
		this.tieCount = tieCount;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Byte getTieRead() {
		return this.tieRead;
	}

	public void setTieRead(Byte tieRead) {
		this.tieRead = tieRead;
	}

	public Byte getReplyRead() {
		return this.replyRead;
	}

	public void setReplyRead(Byte replyRead) {
		this.replyRead = replyRead;
	}

	public Byte getAllpyResultRead() {
		return this.allpyResultRead;
	}

	public void setAllpyResultRead(Byte allpyResultRead) {
		this.allpyResultRead = allpyResultRead;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Set getTUserTiebas() {
		return this.TUserTiebas;
	}

	public void setTUserTiebas(Set TUserTiebas) {
		this.TUserTiebas = TUserTiebas;
	}

	public Set getTTietitles() {
		return this.TTietitles;
	}

	public void setTTietitles(Set TTietitles) {
		this.TTietitles = TTietitles;
	}

}
