package hehetieba.domain;

// Generated 2015-1-30 21:05:08 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TUser generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String nickname;
	private String pwd;
	private String headImg;
	private String introduction;
	private Byte gender;
	private String birthday;
	private Integer tieCount;
	private Date createdDate;
	private Byte tieRead;
	private Byte replyRead;
	private Byte allpyResultRead;
	private Byte enabled;
	private Set userTiebas = new HashSet();
	private Set tieTitles = new HashSet();

	public User() {
	}

	public User(Integer id, String username, Date createdDate) {
		this.id = id;
		this.username = username;
		this.createdDate = createdDate;
	}

	public User(Integer id, String username, String nickname, String password,
			String headImg, String introduction, Byte gender, String birthday,
			Integer tieCount, Date createdDate, Byte tieRead, Byte replyRead,
			Byte allpyResultRead, Byte enabled, Set TUserTiebas,
			Set TTietitles) {
		this.id = id;
		this.username = username;
		this.nickname = nickname;
		this.pwd = password;
		this.headImg = headImg;
		this.introduction = introduction;
		this.gender = gender;
		this.birthday = birthday;
		this.tieCount = tieCount;
		this.createdDate = createdDate;
		this.tieRead = tieRead;
		this.replyRead = replyRead;
		this.allpyResultRead = allpyResultRead;
		this.enabled = enabled;
		this.userTiebas = TUserTiebas;
		this.tieTitles = TTietitles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String password) {
		this.pwd = password;
	}

	public String getHeadImg() {
		return this.headImg;
	}

	public void setHeadImg(String headImg) {
		this.headImg = headImg;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Byte getGender() {
		return this.gender;
	}

	public void setGender(Byte gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Integer getTieCount() {
		return this.tieCount;
	}

	public void setTieCount(Integer tieCount) {
		this.tieCount = tieCount;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Byte getTieRead() {
		return this.tieRead;
	}

	public void setTieRead(Byte tieRead) {
		this.tieRead = tieRead;
	}

	public Byte getReplyRead() {
		return this.replyRead;
	}

	public void setReplyRead(Byte replyRead) {
		this.replyRead = replyRead;
	}

	public Byte getAllpyResultRead() {
		return this.allpyResultRead;
	}

	public void setAllpyResultRead(Byte allpyResultRead) {
		this.allpyResultRead = allpyResultRead;
	}

	public Byte getEnabled() {
		return enabled;
	}

	public void setEnabled(Byte enabled) {
		this.enabled = enabled;
	}

	public Set getUserTiebas() {
		return userTiebas;
	}

	public void setUserTiebas(Set userTiebas) {
		this.userTiebas = userTiebas;
	}

	public Set getTieTitles() {
		return tieTitles;
	}

	public void setTieTitles(Set tieTitles) {
		this.tieTitles = tieTitles;
	}

}
